version: "3.9"

networks:
  main:

services:
  frontend:
    container_name: frontend-react
    hostname: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env       
    networks:
      - main  

