version: "3.9"

networks:
  main:

services:
  server:
    container_name: server
    hostname: server
    build: 
      context: ./backend
      dockerfile: Dockerfile       
    env_file:
      - .env
    command: bash -c "
      uvicorn main:app
      --host 0.0.0.0 --port 8000
      --reload"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - main  

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=databaseuser
      - POSTGRES_DB=databasename
    ports:
      - "1234:5432"
    networks:
      - main  

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true 
    env_file:
      - .env         
    depends_on:
      - server    
    networks:
      - main  

