version: '3'

services:
  server:
    container_name: backend-fastapi
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "
      uvicorn main:app
      --host 0.0.0.0 --port 8000
      --reload
      "
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
